import Header from "@/components/header";
import "./globals.css";
import { Inter } from "next/font/google";
import ActiveSectionContextProvider from "@/context/active-section-context";
import { Toaster } from "react-hot-toast";
const inter = Inter({ subsets: ["latin"] });
import Footer from "@/components/footer";
import ThemeSwitch from "@/components/theme-switch";
import ThemeContextProvider from "@/context/theme-context";
export const metadata = {
  title: "Nathan | Personal Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html className=" !scroll-smooth " lang="en">
      <body
        className={`${inter.className} bg-gray-50 text-gray-950  relative pt-28 sm:pt-36  dark:bg-gray-900 dark:text-gray-50 dark:text-opacity-90`}
      >
        <div className=" bg-[#fbe2e3] -z-10 absolute rounded-full w-[32.5rem] h-[32.5rem] top-[-6rem] right-[11rem] blur-[10rem] sm:w-[68.75rem] dark:bg-[#946263]"></div>
        <div className=" bg-[#dbd7fb] -z-10 absolute rounded-full w-[50rem] h-[32.5rem] top-[-1rem] left-[-35rem] blur-[10rem] sm:w-[68.75rem] md:left-[-33rem] lg:left-[-28rem] xl:left-[-15rem] 2xl:left-[-5rem] dark:bg-[#676394]"></div>
        <ThemeContextProvider>
          <ActiveSectionContextProvider>
            <Header />
            <Toaster position="top-right" />
            {children}
            <Footer />
            <ThemeSwitch />
          </ActiveSectionContextProvider>
        </ThemeContextProvider>
      </body>
    </html>
  );
}
